### ISSUE TITLE
Intelephense disabled NoneType, no attribute cache_path

### ISSUE THREAD

**Issue by sexybiggetje** [sublimelsp/LSP-intelephense#75]
Hi! With the current installed package I have some problems starting lsp-intelephense. I get the following traceback when using the following versions:

Sublime Text: 4126
Sublime-lsp: 1.16.1
lsp-intelephense: 1.0.24

```
Unable to start subprocess for LSP-intelephense
Traceback (most recent call last):
  File "C:\<snip>\Installed Packages\LSP.sublime-package\plugin/core/windows.py", line 246, in start_async
    additional_variables = plugin_class.additional_variables()
  File "C:\<snip>\AppData\Roaming\SUBLIM~1\Packages\LSP_UT~1\st3\lsp_utils\_client_handler\abstract_plugin.py", line 96, in additional_variables
    return cls.get_additional_variables()
  File "C:\<snip>\Installed Packages\LSP-intelephense.sublime-package\plugin.py", line 33, in get_additional_variables
AttributeError: 'NoneType' object has no attribute 'cache_path'
```

**Comment by jfcherng** [comment]
Did you try restarting ST?

**Comment by rchl** [comment]
Or is it an indication that it's not compatible with ST3 anymore?

**Comment by sexybiggetje** [comment]
I restarted the whole machine, which seems to fix it. I often have multiple windows open, so one might have been left open while updating. Thanks, the best fixes are no fixes :D.
